### ISSUE TITLE
Initial WebApp thoughts

### ISSUE THREAD

**Issue by HaffCaff** [CSC-256-Group-Project-9/CsC_256_Group_9_Project#3]
## Problem:
- Decide what we want to do as far as WebApp idea (Do we use Flask or Django?)

## Proposed Solution:
- Discuss what what webapp should be or skeleton of what it should look like (based on reqs of Selenium)

## Potential Issues:
- TBD
## Additional information and reference material:
 - TBD

**Comment by doombot696** [comment]
Django sounds good. I have experience from last last semester in it during my time in the capstone project.
